### ISSUE TITLE
Consider defaulting to SQLite instead of MySQL

### ISSUE THREAD

**Issue by akpu1** [pomf/pomf#11]
At the moment, readme instructs users to install MySQL to get pomf to function (though mentions other databases may work).

MySQL, or any full SQL server, is completely unnecessary (though of course there's nothing wrong with using it) for something like pomf. It is an unnecessary dependency, and complicates installation.  Many might lazily set it up, leaving it in a potentially insecure configuration.

SQLite is completely self-contained, and requires no configuration.  The only change necessary to the code, would be changing the placeholder references to a MySQL server/database in settings.inc.php, to a suitable URI pointing to a location for the SQLite database file.

**Comment by akpu1** [comment]
#13

**Comment by lesderid** [comment]
This is a pretty big change, I wouldn't just accept a pull request without some discussion first.

**Comment by akpu1** [comment]
I'm aware.  I have discussed it with @ewhal and their suggestion was to submit a PR.

This change would not affect existing users if they did not want to switch, though i have written instructions for if they did.

**Comment by akpu1** [comment]
@lesderid in terms of code, it's exceptionally minor
see: https://github.com/pomf/pomf/pull/13/files

**Comment by lesderid** [comment]
I'm aware. Giving instructions to set up SQLite and providing a schema is fine, but I'm not sure if I'd make it the default.

**Comment by akpu1** [comment]
Why?  It is a much more sane default than MySQL IMO

much simpler to setup and maintain, less resource usage, not a network service, less dependencies, closer to evetual goal of no SQL DB

**Comment by lesderid** [comment]
I'm mostly worried about performance issues. Have you tried SQLite with a number of concurrent uploads? Is it as fast or faster than MySQL/MariaDB, even for large databases (such as pomf.se's or mixtape.moe's)? If so, go ahead and merge.

**Comment by akpu1** [comment]
@lesderid not the best answer. but
https://www.sqlite.org/whentouse.html

**Comment by lesderid** [comment]
I'd prefer to see some real-world benchmarks for pomf first. Shouldn't be too hard to do.

**Comment by akpu1** [comment]
Any suggestions for how to do so?  SQLite performs excellently on not-enormous DBs.  Even mixtape.moe is HARDLY that.

**Comment by lesderid** [comment]
Populate a database with fake data (I'd say something like 100k files at least).
Generate some random files (as many as possible) and time how long it takes to upload them concurrently with something like curl.
Then just compare the results with a MySQL-based pomf.

**Comment by akpu1** [comment]
Also may be worth looking at https://www.digitalocean.com/community/tutorials/sqlite-vs-mysql-vs-postgresql-a-comparison-of-relational-database-management-systems

**Comment by akpu1** [comment]
https://pbs.twimg.com/media/CkIq-CEXEAAhecf.jpg:large

Reading performance won't be the issue with SQLite.  If we assume uncached requests are uploads/initial downloads, then these would be the only ones that involwe writing.

https://www.sqlite.org/faq.html#q19
SQLite say that on a 7200RPM desktop hard drive (hardly representative), SQLite can do 60 *transactions* per second.  That is 180x what mixtape.moe was experiencing, on desktop HDDs.

If we divide by 2 because half would be initial downloads 1720580 / 2 = 860290
860290 / (30 days * 86400 sec per day) = 1 request every ~3 sec

**Comment by alucard0134** [comment]
Closing as said in latest comment in #19
