### ISSUE TITLE
[question] maintenance

### ISSUE THREAD

**Issue by obstructive** [pomf/pomf#158]
will this get updated to nunjunks? since [swig is deprecated](https://www.npmjs.com/package/swig) and looks like theres no progress in #28 

(ps: also the outdated php)

**Comment by nokonoko** [comment]
It will get updated to ejs and newer PHP when I get around porting it from Uguu.12 jan. 2023 kl. 03:29 skrev jordan ignacio (igna) ***@***.***>:﻿
will this get updated to nunjunks? since swig is deprecated and looks like theres no progress in #28
(ps: also the outdated php)
