### ISSUE TITLE
Unbloat readme

### ISSUE THREAD

**Issue by alucard0134** [pomf/pomf#22]
We are moving to readthedocs since the readme file is getting quite large now, but is still widely unfinished, you can contribute to pomf-docs to finish it

also obligatory @pomf/documentation

**Comment by ileyd** [comment]
Hi,

I am working on rewriting the documentation and planned to rewrite the readme as part of this.  I've left it as is for completeness, for now, as there is not yet comparable documentation on readthedocs.
