### ISSUE TITLE
Configuration examples should not be in git repository

### ISSUE THREAD

**Issue by liilac** [pomf/pomf#23]
@ewhal 
https://github.com/pomf/pomf/tree/master/confs

Configuration examples do not belong in the git repository, especially the main one.  The best place for them would be in the documentation.

**Comment by ewhal** [comment]
I also agree and we want to move this to documentation.

**Comment by alucard0134** [comment]
once readthedocs is fully up we can remove them, until then they are kinda needed, or we can just add a page into the github wiki until then for them

**Comment by alucard0134** [comment]
assigned to docs team
