### ISSUE TITLE
Do not rewrite changlelog history

### ISSUE THREAD

**Issue by ileyd** [pomf/pomf#24]
@ewhal 
https://github.com/pomf/pomf/commit/b0ccd22c1c35bac16699282cad77e664f698126d

Unless they were never true in the first place, you should *not* remove changelog entries.  This is akin to rewriting public git history.  You should instead create a new entry, clarifying the previous was undone.

**Comment by ewhal** [comment]
Those commits weren't approved in the first place but I understand what you mean

**Comment by ileyd** [comment]
@ewhal 
unapproved is still committed.  You're basically lying about what happened (of no consequence, but still)
