### ISSUE TITLE
JS clipboard button

### ISSUE THREAD

**Issue by ewhal** [pomf/pomf#25]
Introduce buttons like on 1339.cf

**Comment by alucard0134** [comment]
notes:
https://hacks.mozilla.org/2015/09/flash-free-clipboard-for-the-web/
http://stackoverflow.com/a/30810322

**Comment by ileyd** [comment]
^implemented with @alucard0134's permission :stuck_out_tongue:

**Comment by alucard0134** [comment]
added in 4a869e4e0e1368baf5aa4e1a4144e0d31f633782
