### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by ewhal** [pomf/pomf#26]

**Comment by ileyd** [comment]
I would be happy to write this, and might do so later today.

**Comment by ewhal** [comment]
@NuckChorris said he was willing to do it and he is more experienced in it.
I'm not terribly sure how to properly do it with docker-compose and I'd rather leave it up to someone with experience.

**Comment by bfayers** [comment]
Is there any update on this? It's nearly been a year and I'm wanting to run this

**Comment by nokonoko** [comment]
nah
