### ISSUE TITLE
Migrate to bootstrap v4 or flexboxes 

### ISSUE THREAD

**Issue by ewhal** [pomf/pomf#29]

**Comment by NuckChorris** [comment]
Lol why would you migrate to bootstrap? Do you desire 100x larger CSS?

Flexbox could be good though, you can actually center the button on page that way

**Comment by lesderid** [comment]
I think you can customise Bootstrap and get rid of all the bloat? I 
don't know how effective it is though.

Flexbox is a good idea though.
