### ISSUE TITLE
Custom Expire Options

### ISSUE THREAD

**Issue by alucard0134** [pomf/pomf#37]
Make a dropdown table for expiration options ex:

1 hour
12 hours
1 day
1 week
1 month
@pomf/developers pls

**Comment by ewhal** [comment]
I personally don't want to have this in the main project.

**Comment by alucard0134** [comment]
it can be an extension and/or a manual addition into the makefile (ex --with-expire)

**Comment by ewhal** [comment]
I was thinking keep it in a separate repo and make it a submodule.

**Comment by alucard0134** [comment]
yeah I agree with that

**Comment by ileyd** [comment]
Well, (keep in mind I would be happy to write this actually), the actual code for this would not be very large at all, and it could easily be kept as a configurable option.  This would comprise maybe 6 lines.

I do however understand a desire to avoid inflating the pomf code *at all*

**Comment by ewhal** [comment]
I've just split the pomf project into different repos now anyway so it no longer should be in pomf itself but rather as a submodule.

**Comment by alucard0134** [comment]
@ileyd ditto to what @ewhal said.

**Comment by ileyd** [comment]
@ewhal or @NuckChorris 

Would one of you please create a repository called "file-expiry", and grant me write access or higher?

**Comment by ileyd** [comment]
This is slightly complicated actually.  The code itself to do this is very straightforward, but I'm trying to think how to do this as a submodule.  

Almost *none* of the code is independent; it's all additions to existing files: `upload_form.swig`, `upload.php` and `dist.json`.

The only part that isn't would be a one-line cron script.

**Comment by alucard0134** [comment]
I personally don't mind it being built in, will a configuration option to disable it be possible?

**Comment by ileyd** [comment]
@alucard0134 absolutely

**Comment by alucard0134** [comment]
I would proceed with that then

**Comment by happy-box** [comment]
I did it already.
https://github.com/happy-box/Pomf_Expirey_Support

**Comment by alucard0134** [comment]
has to be js also @happy-box

**Comment by happy-box** [comment]
@alucard0134 js is botnet

**Comment by lesderid** [comment]
This should not be in the main project.

**Comment by ileyd** [comment]
@lesderid could you explain why?  This can easily be implemented as a configurable option, and having it be external necessitates patch files the user has to run.  

Although I suppose I could add it to the Makefile and have it selected via the MODULES variable like the others.

**Comment by lesderid** [comment]
It's outside the scope of pomf.

**Comment by alucard0134** [comment]
@lesderid then why was it in the original pomf code :V

**Comment by lesderid** [comment]
because neku

**Comment by alucard0134** [comment]
neku is god
neku is life

**Comment by NuckChorris** [comment]
I don't see why it would be outside the scope of pomf. The original plan was to provide expiry options but we just never built it into pomf itself. So instead neku did uguu.se, which provided the sane feature in an uglier package. But it was always on my roadmap and I had a few prototypes

**Comment by lesderid** [comment]
Fair enough.
