### ISSUE TITLE
Comment all code

### ISSUE THREAD

**Issue by ewhal** [pomf/pomf#40]
- static/js/
  - [x] app.js
- static/css
  - [x] pomf.css
- php/
  - [x] upload.php
  - [x] grill.php
  - classes/
    - [x] Response.class.php
    - [x] UploadException.class.php
    - [x] UploadedFile.class.php
- moe/
  - [ ] index.php
  - panel/
    - [ ] index.php
    - [ ] search.php
  - includes/
    - [ ] api.php
    - [ ] core.php
    - [x] settings.inc.php

**Comment by r3c0d3x** [comment]
You should edit the issue description to have a list of checkboxes for all files containing code in need of comments, so we can visually see what we need to work on. 

Maybe something like:

- dir
    - [x] blah.css
    - [ ] blah2.js
- dir2
   - [x] blah3.php

**Comment by alucard0134** [comment]
Waiting PR, no work needed

**Comment by alucard0134** [comment]
app.js commented in 7c4688a9b21e5d18e4ad34111c168755013a3a7a
