### ISSUE TITLE
Write separate Makefiles for submodules

### ISSUE THREAD

**Issue by ileyd** [pomf/pomf#41]
As they are intended to be independent, they should have their own Makefiles.  Note, this will **not** require them to be run separately; they will be run recursively from the main Makefile when specified.

I am happy to write them at some point, so feel free to assign me to this.

**Comment by ileyd** [comment]
Actually, now that I've though about it, I'm not entirely sure of the utility of this.  All the existing submodules (moe and php), at the moment, consist of entirely static content, and nothing is done to their directory structure.

All the Makefile would be able to do, other than installing into place, is generate an archive of the contents (`make dist`).

Input?  It's something that would take thirty seconds each, either way.

**Comment by alucard0134** [comment]
it would be coming to a point where we would just keep on piling steps and making the issue of how bloody hard it is to setup pomf worse

So closing
