### ISSUE TITLE
Javascript 2nd copy button doesn't work 

### ISSUE THREAD

**Issue by ewhal** [pomf/pomf#45]
All copy buttons except the first one don't work in chromium 51.0.2704.84 (Developer Build) (64-bit).
When clicked they return the error 'Discontiguous selection is not supported.(anonymous function) @ pomf.min.js'

**Comment by r3c0d3x** [comment]
Cannot reproduce on Chrome "v51.0.2704.103 m" or Chrome "v51.0.2704.106 m" using [cuntflaps.me](https://cuntflaps.me). Haven't checked with Chromium though.

**Comment by ewhal** [comment]
Discontiguous selection is not supported.(anonymous function) @ pomf.min.js:100

**Comment by alucard0134** [comment]
chrome://version/ @ewhal

**Comment by ewhal** [comment]
http://i.imgur.com/k8UW2PL.png

**Comment by r3c0d3x** [comment]
https://i.imgur.com/0Bqvydv.png

**Comment by alucard0134** [comment]
can confirm reproduction on latest stable and canary chrome builds.

Steps to reproduce:

1. Upload multiple files
2. Attempt to copy the first file link

Expected action is for the link to be copied to the clipboard, however Chrome returns a Discontiguous selection is not supported error

cc'ing @ileyd

**Comment by alucard0134** [comment]
while firefox will not flat-out refuse copying, it copies two links improperly, with both of them being copied example: a.cuntflaps.me/yfdafd.txthttps://a.cuntflaps.me/ywxefq

**Comment by ileyd** [comment]
I'll take a look at this.  I only tested on Firefox when I wrote it; didn't relaly think there would be a reason for it to be any different on other browsers.

**Comment by ileyd** [comment]
@alucard0134 it works fine for me on firefox with multiple links

**Comment by ewhal** [comment]
I experienced the same thing as @alucard0134 on firefox as well

**Comment by alucard0134** [comment]
@ileyd and it pastes properly as well?

**Comment by ileyd** [comment]
Investigating atm

**Comment by ileyd** [comment]
Believe I have fixed this issue.  Creating a PR.
