### ISSUE TITLE
Filename sanitization 

### ISSUE THREAD

**Issue by odilitime** [pomf/pomf#48]
I just saw a original filename with single quotes around it
so the extension ended with a single quote

originalfilename: 'filename.ext'
filename: asdfe.ext'

not sure this is desired, just bringing it to your attention.

**Comment by ileyd** [comment]
as clsr mentioned, this is acceptable for filenames

there is nothing wrong with this.  the only concern is for SQL injection, which is solved with escaped user input like everything should be

**Comment by odilitime** [comment]
Well it's making our extensions statistics incorrect, so we'll just fix it in our copy

**Comment by ileyd** [comment]
that is a problem with extension statistics code though

**Comment by ileyd** [comment]
SQL injection is not an issue due to the way handled in the code.
URLs are now properly handled.

All should be good now.  @ewhal

**Comment by alucard0134** [comment]
side note: this is a pomf-php issue
