### ISSUE TITLE
Filename URL encoding

### ISSUE THREAD

**Issue by odilitime** [pomf/pomf#49]
We do not handle URL generation properly: {"success":true,"files":[{"hash":"f56c05af7e48906f27de6f2b24f79339cbd0084a","name":"test.foo bar","url":"https:\/\/my.mixtape.moe\/vnbgno.foo bar","size":14}]}

should've been /vnbgno.foo%20bar
The file extension doesn't seem to be URL encoded.

(can ask cslr on IRC)

**Comment by ileyd** [comment]
http://php.net/manual/en/function.urlencode.php

**Comment by ewhal** [comment]
Only json urls are encoded properly in the recent merge.
Doesn't escape all response types
