### ISSUE TITLE
Hash algorithm migration supposed to be completed

### ISSUE THREAD

**Issue by ileyd** [pomf/pomf#51]
https://github.com/pomf/pomf-php/blob/master/classes/UploadedFile.class.php

This is not horribly difficult to do.  There are two components
- replace SHA-1 with SHA-2 in above
- replace all existing hashes in DB with new one

The latter would be CPU intensive, so running it may need to be planned (and ensuring it has low nice value, etc).  It should not be very difficult to generate new hashes in the background, then when ready, use new code that checks SHA-2 hashes.

**Comment by lesderid** [comment]
What's the reasoning behind switching to SHA-2 hashes?

**Comment by ileyd** [comment]
No idea tbh 😋

**Comment by ileyd** [comment]
Ask Wub? 😉

**Comment by lesderid** [comment]
Let's not.

**Comment by alucard0134** [comment]
is there a reason to switch to SHA-2 while SHA-1 works fine @ileyd?

**Comment by ewhal** [comment]
I forgot to remove all of wub's deprecation notices. SHA1 is still fine for something like pomf so no real reason to switch.
