### ISSUE TITLE
raw TCP upload interface

### ISSUE THREAD

**Issue by the8472** [pomf/pomf#55]
Supporting upload through netcat on a separate port, like http://termbin.com/ does would be great to allow uploads from unixy systems without additional dependencies.

**Comment by lesderid** [comment]
Way outside of pomf's scope. curl works just fine if you want a CLI interface.

**Comment by the8472** [comment]
Maybe mentioning that on the tools page then?

**Comment by NuckChorris** [comment]
If you don't know about curl you shouldn't be using Unix

—Peter

**Comment by the8472** [comment]
You still need the right http request parameters. I don't see them anywhere on the docs.

Of course I can extract them from the browser logs, but that's not exactly documentation.

**Comment by ewhal** [comment]
Look at the scripts on tools.html

**Comment by alucard0134** [comment]
Also readthedocs

**Comment by the8472** [comment]
Good enough I guess. I would have preferred it on the tools.html, but whatever.

**Comment by ewhal** [comment]
pull requests welcome if you want to add it.
