### ISSUE TITLE
Allow uploading from URL

### ISSUE THREAD

**Issue by itslukej** [pomf/pomf#59]
I would expect this to be used like

```python
requests.post(
    "http://pomf.website/upload.php",
    data="http://image.url/here"
)
```

**Comment by nokonoko** [comment]
Might add this as an option, it would allow for a lot of abuse tho.

**Comment by HT-7** [comment]
I recommend making it optional so the server owner can decide.

> it would allow for a lot of abuse tho.

Any more than normal uploading?

**Comment by nokonoko** [comment]
Since I've decided to not update Pomf anymore, seeing as Uguu has the same functionality, lets take this issue to Uguu instead. Do you mind opening the same issue?
