### ISSUE TITLE
merge pomf-php into pomf

### ISSUE THREAD

**Issue by alucard0134** [pomf/pomf#60]
Well apparently I have mood swings about this but the gist cats_ made in #pomfret (https://gist.github.com/alucard0134/b5e5e80f68980aa27a5f35cf2a9b0a62) quoting "holy sSSHIT MAKE SURE YOU HAVE --recursive BECAUSE SOMEONE THOUGHT IT'D BE GREAT TO PUT THE PHP FILES IN A FUCKING SUB MODULE (LIKE THEY'RE OPTIONAL??)" 

From the git doc on submodules: 
"It often happens that while working on one project, you need to use another project from within it. Perhaps it’s a library that a third party developed or that you’re developing separately and using in multiple parent projects. A common issue arises in these scenarios: you want to be able to treat the two projects as separate yet still be able to use one from within the other."

The php project meets none in the criteria. It is a requirement of the project, but should not be part of its own repo due too it being an integral part of pomf which cannot be replaced (atm)

**Comment by ewhal** [comment]
Technically it can be replaced and most certainly has been in a number of cases.
It separates the frontend and the backend so if someone wants to write a different implementation of pomf they can use the frotend with no bull.

**Comment by LolcatsV2** [comment]
If someone is going through the trouble of rewriting a backend for pomf, odds are they're not going to bother compiling pomf just for its front-end. Just merge them already. It's a part of pomf integrally and only serves to cause confusion when cloning.

**Comment by alucard0134** [comment]
resolved in https://github.com/pomf/pomf/commit/b4fc2f892b877fe0cfb90063248d720bf87b49c8
