### ISSUE TITLE
remove sqlite

### ISSUE THREAD

**Issue by alucard0134** [pomf/pomf#63]
It was a shitty implementation and would even require a re-write of moe to make it work.

Suggest we remove it altogether as I don't know any clone who would bother with it.

**Comment by ewhal** [comment]
no

**Comment by lesderid** [comment]
Why was this issue closed?

**Comment by ewhal** [comment]
Cause no reason to actually remove sqlite

**Comment by lesderid** [comment]
What about @alucard0134's concerns?
