### ISSUE TITLE
Prevent others from uploading to server

### ISSUE THREAD

**Issue by Dooleylabs** [pomf/pomf#65]
It's probably been documented somewhere and asked before, but what can I do to prevent random people from uploading to my private pomf? I'd prefer an api or user/password solution if possible that is compatible with ShareX.

Thank you.

**Comment by lesderid** [comment]
This is beyond the scope of pomf.

Use HTTP Basic Authentication in your web server.

**Comment by LolcatsV2** [comment]
This isn't really suited for an Issue request - Help with pomf is better found at Rizon IRC - channel #pomfret. We won't code anything for you, but can answer most questions. lesderid's answer is a good start if you want.

**Comment by Dooleylabs** [comment]
I've decided to go the anonymous route and rename my upload.php. If that doesn't work, I'll look into Basic Auth. Thank you.

**Comment by ewhal** [comment]
sr.ht is a good solution to this
