### ISSUE TITLE
Uncaught Error: Call to member function bindValue()

### ISSUE THREAD

**Issue by Trekintosh** [pomf/pomf#66]
Good day. I've never used Pomf before, so excuse me if this is obvious and I'm stupid.

I've got an instance running Ubuntu 16.04, with SQlite3 and NGinx running on it. I set up the Pomf database as per the instructions and it all seems correct. I'm trying to use Pomf on my website. I've got it all running but when I try to upload a file, the status bar goes up, then at 100% it just says Server Error!

Going to /var/logs/nginx/error.log and I find that it's thrown this error:

`2017/09/12 16:12:33 [error] 7441#7441: *7 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to a member function bindValue() on boolean $
Stack trace:
#0 /var/www/pics/upload.php(228): uploadFile(Object(UploadedFile))
#1 {main}
  thrown in /var/www/pics/upload.php on line 107" while reading response header from upstream, client: 68.233.207.162, server: pics.trekintosh.com, request: "POST $`

Can anyone shed some light on this for me? Am I just being stupid or is it a genuine issue?

**Comment by LolcatsV2** [comment]
Your database isn't configured properly. Just use Mysql and follow the guide at https://catbox.moe/retard.html

**Comment by M1noa** [comment]
I love how theirs a hidden catbox.moe page I found when checking the robots.txt
