### ISSUE TITLE
How hard is to integrate with amazon s3?

### ISSUE THREAD

**Issue by Yokutto** [pomf/pomf#70]
The title says it all

**Comment by LolcatsV2** [comment]
Preface: This would be a horrible idea.

To answer your question firstly: integrating with AWS S3 is actually fairly easy. You'll just need the [AWS SDK for PHP](https://aws.amazon.com/sdk-for-php/) and set up uploads to use S3 import code.

However, I would warn you against using S3 for anything public facing. S3 has incredibly high bandwidth costs for outgoing bandwidth, and really there isn't a reason to use S3 over a cheap VPS. The only reason I can see why you'd do this is to have a private instance for files that only you would have access to. But at that point, why not just make a cheap FTP server?

**Comment by Yokutto** [comment]
That's simple. The S3 just give me a high availability for the files, idc about the costs.
The bandwidth can be limited if the file is downloaded too many times.

I had a server that have more than 100k of files in one folder and the performance is really bad, I can't even list the files in directory without server load increase a lot.

I will install pomf with AWS SDK and see what happens, if amazon charge me a lot I will update this issue feedback, thanks for all 👍
